name: pyclub

description: Appli conçu pour les membres du club python de la filère Miage de l'UFHB.
version: 1.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  percent_indicator: ^2.1.3
  simple_animations: ^1.3.3
  image_picker: ^0.8.4+4
  pull_to_refresh: ^2.0.0
  material_dialogs:
  ndialog: ^4.1.0
  splash_screen_view:
  shared_preferences: any
  select_dialog: any
  shimmer: any
  # connectivity_plus: any
  flutter_bloc: any
  data_connection_checker: any
  # firebase_auth: 
  # firebase_core: 
  flutter_svg: ^1.0.0
  google_fonts: ^2.2.0
  intl: ^0.17.0
  get:
  url_launcher: ^6.0.9
  # cloud_firestore: ^2.5.1
  dio: ^4.0.4
  http: ^0.13.3
  fluttertoast: ^8.0.8
  # firebase_database:
  dart_eval: ^0.0.4
  # device_preview: ^1.0.0
dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/py_logo.png" 
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  